# <meta>
#    <source>@pssbletrngle/github-meta-generator</source>
#    <version>1.0.100</version>
#    <timestamp>2026-06-22T09:00:07.261Z</timestamp>
#    <hash>d37cd3dba38e6a39</hash>
# </meta>

name: Trigger Semantic Release

permissions:
  contents: read
  actions: write

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: release.yml
          inputs: '{ "version": "${{ github.event.release.tag_name }}" }'
